---
title: Control de errores de E/S en .NET
description: Aprenda a controlar errores de E/S en .NET. Asigne códigos de error a excepciones, controle excepciones en operaciones de E/S y controle IOException.
ms.date: 08/27/2018
ms.technology: dotnet-standard
dev_langs:
- csharp
- vb
helpviewer_keywords:
- I/O, exception handling
- I/O, errors
ms.workload:
- dotnet
- dotnetcore
ms.openlocfilehash: bd7112b3052f246a01e4a36d6d425b37cb6174dd
ms.sourcegitcommit: 7588b1f16b7608bc6833c05f91ae670c22ef56f8
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 11/02/2020
ms.locfileid: "93188047"
---
# <a name="handling-io-errors-in-net"></a><span data-ttu-id="63b3b-104">Control de errores de E/S en .NET</span><span class="sxs-lookup"><span data-stu-id="63b3b-104">Handling I/O errors in .NET</span></span>

<span data-ttu-id="63b3b-105">Además de las excepciones que se pueden producir en cualquier llamada al método (como <xref:System.OutOfMemoryException> cuando un sistema está sobrecargado o <xref:System.NullReferenceException> debido a errores de programador), los métodos del sistema de archivos de .NET pueden producir las excepciones siguientes:</span><span class="sxs-lookup"><span data-stu-id="63b3b-105">In addition to the exceptions that can be thrown in any method call (such as an <xref:System.OutOfMemoryException> when a system is stressed or an <xref:System.NullReferenceException> due to programmer error), .NET file system methods can throw the following exceptions:</span></span>

- <span data-ttu-id="63b3b-106"><xref:System.IO.IOException?displayProperty=nameWithType>, la clase base de todos los tipos de excepción <xref:System.IO>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-106"><xref:System.IO.IOException?displayProperty=nameWithType>, the base class of all <xref:System.IO> exception types.</span></span> <span data-ttu-id="63b3b-107">Se produce por errores cuyos códigos de retorno del sistema operativo no se asignan directamente a cualquier otro tipo de excepción.</span><span class="sxs-lookup"><span data-stu-id="63b3b-107">It is thrown for errors whose return codes from the operating system don't directly map to any other exception type.</span></span>
- <span data-ttu-id="63b3b-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="63b3b-114"><xref:System.ArgumentException?displayProperty=nameWithType>, que se produce para caracteres de ruta no válidos en .NET Framework y en .NET Core 2.0 y versiones anteriores.</span><span class="sxs-lookup"><span data-stu-id="63b3b-114"><xref:System.ArgumentException?displayProperty=nameWithType>, which is thrown for invalid path characters on .NET Framework and on .NET Core 2.0 and previous versions.</span></span>
- <span data-ttu-id="63b3b-115"><xref:System.NotSupportedException?displayProperty=nameWithType>, que se produce para dos puntos no válidos en .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="63b3b-115"><xref:System.NotSupportedException?displayProperty=nameWithType>, which is thrown for invalid colons in .NET Framework.</span></span>
- <span data-ttu-id="63b3b-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>, que se produce para las aplicaciones que se ejecutan con confianza limitada y que carecen de los permisos necesarios solo en .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="63b3b-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>, which is thrown for applications running in limited trust that lack the necessary permissions on .NET Framework only.</span></span> <span data-ttu-id="63b3b-117">(La plena confianza es el valor predeterminado en .NET Framework).</span><span class="sxs-lookup"><span data-stu-id="63b3b-117">(Full trust is the default on .NET Framework.)</span></span>

## <a name="mapping-error-codes-to-exceptions"></a><span data-ttu-id="63b3b-118">Asignación de códigos de error a excepciones</span><span class="sxs-lookup"><span data-stu-id="63b3b-118">Mapping error codes to exceptions</span></span>

<span data-ttu-id="63b3b-119">Dado que el sistema de archivos es un recurso del sistema operativo, los métodos de E/S de .NET Core y .NET Framework encapsulan llamadas en el sistema operativo subyacente.</span><span class="sxs-lookup"><span data-stu-id="63b3b-119">Because the file system is an operating system resource, I/O methods in both .NET Core and .NET Framework wrap calls to the underlying operating system.</span></span> <span data-ttu-id="63b3b-120">Cuando se produce un error de E/S en el código ejecutado por el sistema operativo, el sistema operativo devuelve información de error para el método de E/S de .NET.</span><span class="sxs-lookup"><span data-stu-id="63b3b-120">When an I/O error occurs in code executed by the operating system, the operating system returns error information to the .NET I/O method.</span></span> <span data-ttu-id="63b3b-121">El método después traduce la información de error, normalmente en forma de un código de error, en un tipo de excepción de .NET.</span><span class="sxs-lookup"><span data-stu-id="63b3b-121">The method then translates the error information, typically in the form of an error code, into a .NET exception type.</span></span> <span data-ttu-id="63b3b-122">En la mayoría de los casos, lo hace convirtiendo directamente el código de error en su correspondiente tipo de excepción; no realiza ninguna asignación especial del error en función del contexto de la llamada al método.</span><span class="sxs-lookup"><span data-stu-id="63b3b-122">In most cases, it does this by directly translating the error code into its corresponding exception type; it does not perform any special mapping of the error based on the context of the method call.</span></span>

<span data-ttu-id="63b3b-123">Por ejemplo, en el sistema operativo Windows, una llamada al método que devuelve un código de error `ERROR_FILE_NOT_FOUND`, o bien 0 x 02, se asigna a <xref:System.IO.FileNotFoundException>, y un código de error `ERROR_PATH_NOT_FOUND`, o bien 0 x 03, se asigna a <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-123">For example, on the Windows operating system, a method call that returns an error code of `ERROR_FILE_NOT_FOUND` (or 0x02) maps to a <xref:System.IO.FileNotFoundException>, and an error code of `ERROR_PATH_NOT_FOUND` (or 0x03) maps to a <xref:System.IO.DirectoryNotFoundException>.</span></span>

<span data-ttu-id="63b3b-124">Sin embargo, las condiciones precisas en las que el sistema operativo devuelve códigos de error concretos no suelen estar documentadas o, en caso de estarlo, la documentación suele ser escasa.</span><span class="sxs-lookup"><span data-stu-id="63b3b-124">However, the precise conditions under which the operating system returns particular error codes is often undocumented or poorly documented.</span></span> <span data-ttu-id="63b3b-125">Como resultado, pueden producirse excepciones inesperadas.</span><span class="sxs-lookup"><span data-stu-id="63b3b-125">As a result, unexpected exceptions can occur.</span></span> <span data-ttu-id="63b3b-126">Por ejemplo, puesto que está trabajando con un directorio en lugar de un archivo, cabría esperar que proporcionar una ruta de acceso de directorio no válida para el constructor <xref:System.IO.DirectoryInfo.%23ctor%2A> produzca <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-126">For example, because you are working with a directory rather than a file, you would expect that providing an invalid directory path to the <xref:System.IO.DirectoryInfo.%23ctor%2A> constructor throws a <xref:System.IO.DirectoryNotFoundException>.</span></span> <span data-ttu-id="63b3b-127">Sin embargo, también puede producir <xref:System.IO.FileNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-127">However, it may also throw a <xref:System.IO.FileNotFoundException>.</span></span>

## <a name="exception-handling-in-io-operations"></a><span data-ttu-id="63b3b-128">Control de excepciones en operaciones de E/S</span><span class="sxs-lookup"><span data-stu-id="63b3b-128">Exception handling in I/O operations</span></span>

<span data-ttu-id="63b3b-129">Debido a esta dependencia en el sistema operativo, condiciones de excepción idénticas (como el caso en que el directorio no encontró el error en nuestro ejemplo) pueden dar lugar a que un método de E/S genere cualquier clase entera de excepciones de E/S.</span><span class="sxs-lookup"><span data-stu-id="63b3b-129">Because of this reliance on the operating system, identical exception conditions (such as the directory not found error in our example) can result in an I/O method throwing any one of the entire class of I/O exceptions.</span></span> <span data-ttu-id="63b3b-130">Esto significa que, al llamar a API de E/S, el código debe prepararse para controlar la mayoría de estas excepciones o todas, como se muestra en la siguiente tabla:</span><span class="sxs-lookup"><span data-stu-id="63b3b-130">This means that, when calling I/O APIs, your code should be prepared to handle most or all of these exceptions, as shown in the following table:</span></span>

| <span data-ttu-id="63b3b-131">Tipo de excepción</span><span class="sxs-lookup"><span data-stu-id="63b3b-131">Exception type</span></span> | <span data-ttu-id="63b3b-132">.NET Core, y .NET 5 y versiones posteriores</span><span class="sxs-lookup"><span data-stu-id="63b3b-132">.NET Core/.NET 5+</span></span> | <span data-ttu-id="63b3b-133">.NET Framework</span><span class="sxs-lookup"><span data-stu-id="63b3b-133">.NET Framework</span></span> |
|---|---|---|
| <xref:System.IO.IOException> | <span data-ttu-id="63b3b-134">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-134">Yes</span></span> | <span data-ttu-id="63b3b-135">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-135">Yes</span></span> |
| <xref:System.IO.FileNotFoundException> | <span data-ttu-id="63b3b-136">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-136">Yes</span></span> | <span data-ttu-id="63b3b-137">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-137">Yes</span></span> |
| <xref:System.IO.DirectoryNotFoundException> | <span data-ttu-id="63b3b-138">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-138">Yes</span></span> | <span data-ttu-id="63b3b-139">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-139">Yes</span></span> |
| <xref:System.IO.DriveNotFoundException?> | <span data-ttu-id="63b3b-140">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-140">Yes</span></span> | <span data-ttu-id="63b3b-141">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-141">Yes</span></span> |
| <xref:System.IO.PathTooLongException> | <span data-ttu-id="63b3b-142">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-142">Yes</span></span> | <span data-ttu-id="63b3b-143">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-143">Yes</span></span> |
| <xref:System.OperationCanceledException> | <span data-ttu-id="63b3b-144">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-144">Yes</span></span> | <span data-ttu-id="63b3b-145">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-145">Yes</span></span> |
| <xref:System.UnauthorizedAccessException> | <span data-ttu-id="63b3b-146">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-146">Yes</span></span> | <span data-ttu-id="63b3b-147">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-147">Yes</span></span> |
| <xref:System.ArgumentException> | <span data-ttu-id="63b3b-148">.NET Core 2.0 y versiones anteriores</span><span class="sxs-lookup"><span data-stu-id="63b3b-148">.NET Core 2.0 and earlier</span></span>| <span data-ttu-id="63b3b-149">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-149">Yes</span></span> |
| <xref:System.NotSupportedException> | <span data-ttu-id="63b3b-150">No</span><span class="sxs-lookup"><span data-stu-id="63b3b-150">No</span></span> | <span data-ttu-id="63b3b-151">Sí</span><span class="sxs-lookup"><span data-stu-id="63b3b-151">Yes</span></span> |
| <xref:System.Security.SecurityException> | <span data-ttu-id="63b3b-152">No</span><span class="sxs-lookup"><span data-stu-id="63b3b-152">No</span></span> | <span data-ttu-id="63b3b-153">Confianza limitada solo</span><span class="sxs-lookup"><span data-stu-id="63b3b-153">Limited trust only</span></span> |

## <a name="handling-ioexception"></a><span data-ttu-id="63b3b-154">Control de excepciones de E/S</span><span class="sxs-lookup"><span data-stu-id="63b3b-154">Handling IOException</span></span>

<span data-ttu-id="63b3b-155">Como la clase base para las excepciones en el espacio de nombres <xref:System.IO>, también se produce <xref:System.IO.IOException> para cualquier código de error que no se asigna a un tipo de excepción predefinido.</span><span class="sxs-lookup"><span data-stu-id="63b3b-155">As the base class for exceptions in the <xref:System.IO> namespace, <xref:System.IO.IOException> is also thrown for any error code that does not map to a predefined exception type.</span></span> <span data-ttu-id="63b3b-156">Esto significa que se puede iniciar con cualquier operación de E/S.</span><span class="sxs-lookup"><span data-stu-id="63b3b-156">This means that it can be thrown by any I/O operation.</span></span>

> [!IMPORTANT]
> <span data-ttu-id="63b3b-157">Dado que <xref:System.IO.IOException> es la clase base de los otros tipos de excepción en el espacio de nombres <xref:System.IO>, se debe controlar en un bloque `catch` después de haber controlado las otras excepciones relacionadas con E/S.</span><span class="sxs-lookup"><span data-stu-id="63b3b-157">Because <xref:System.IO.IOException> is the base class of the other exception types in the <xref:System.IO> namespace, you should handle in a `catch` block after you've handled the other I/O-related exceptions.</span></span>

<span data-ttu-id="63b3b-158">Además, a partir de .NET Core 2.1, se han quitado las comprobaciones de validación de la exactitud de la ruta de acceso (por ejemplo, para asegurarse de que los caracteres no válidos no están presentes en una ruta de acceso), y el tiempo de ejecución produce una excepción que se asigna desde un código de error del sistema operativo y no desde su propio código de validación.</span><span class="sxs-lookup"><span data-stu-id="63b3b-158">In addition, starting with .NET Core 2.1, validation checks for path correctness (for example, to ensure that invalid characters are not present in a path) have been removed, and the runtime throws an exception mapped from an operating system error code rather than from its own validation code.</span></span> <span data-ttu-id="63b3b-159">La excepción que es más probable que se produzca en este caso es <xref:System.IO.IOException>, aunque también podría generarse cualquier otro tipo de excepción.</span><span class="sxs-lookup"><span data-stu-id="63b3b-159">The most likely exception to be thrown in this case is an <xref:System.IO.IOException>, although any other exception type could also be thrown.</span></span>

<span data-ttu-id="63b3b-160">Tenga en cuenta que, en el código de control de excepciones, siempre debe controlar la última clase <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-160">Note that, in your exception handling code, you should always handle the <xref:System.IO.IOException> last.</span></span> <span data-ttu-id="63b3b-161">De lo contrario, como se trata de la clase base de todas las excepciones de E/S, los bloques catch de las clases derivadas no se evaluarán.</span><span class="sxs-lookup"><span data-stu-id="63b3b-161">Otherwise, because it is the base class of all other IO exceptions, the catch blocks of derived classes will not be evaluated.</span></span>

<span data-ttu-id="63b3b-162">Si se trata de <xref:System.IO.IOException>, puede obtener información de error adicional de la propiedad [IOException.HResult](xref:System.Exception.HResult).</span><span class="sxs-lookup"><span data-stu-id="63b3b-162">In the case of an <xref:System.IO.IOException>, you can get additional error information from the [IOException.HResult](xref:System.Exception.HResult) property.</span></span> <span data-ttu-id="63b3b-163">Para convertir el valor HResult en un código de error de Win32, quite los 16 bits superiores del valor de 32 bits.</span><span class="sxs-lookup"><span data-stu-id="63b3b-163">To convert the HResult value to a Win32 error code, you strip out the upper 16 bits of the 32-bit value.</span></span> <span data-ttu-id="63b3b-164">En la tabla siguiente se enumeran los códigos de error que pueden encapsularse en <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="63b3b-164">The following table lists error codes that may be wrapped in an <xref:System.IO.IOException>.</span></span>

| <span data-ttu-id="63b3b-165">HResult</span><span class="sxs-lookup"><span data-stu-id="63b3b-165">HResult</span></span> | <span data-ttu-id="63b3b-166">Constante</span><span class="sxs-lookup"><span data-stu-id="63b3b-166">Constant</span></span> | <span data-ttu-id="63b3b-167">Descripción</span><span class="sxs-lookup"><span data-stu-id="63b3b-167">Description</span></span> |
| --- | --- | --- |
| <span data-ttu-id="63b3b-168">ERROR_SHARING_VIOLATION</span><span class="sxs-lookup"><span data-stu-id="63b3b-168">ERROR_SHARING_VIOLATION</span></span> | <span data-ttu-id="63b3b-169">32</span><span class="sxs-lookup"><span data-stu-id="63b3b-169">32</span></span> | <span data-ttu-id="63b3b-170">Falta el nombre de archivo, o el archivo o directorio está en uso.</span><span class="sxs-lookup"><span data-stu-id="63b3b-170">The file name is missing, or the file or directory is in use.</span></span> |
| <span data-ttu-id="63b3b-171">ERROR_FILE_EXISTS</span><span class="sxs-lookup"><span data-stu-id="63b3b-171">ERROR_FILE_EXISTS</span></span> | <span data-ttu-id="63b3b-172">80</span><span class="sxs-lookup"><span data-stu-id="63b3b-172">80</span></span> | <span data-ttu-id="63b3b-173">El archivo ya existe.</span><span class="sxs-lookup"><span data-stu-id="63b3b-173">The file already exists.</span></span> |
| <span data-ttu-id="63b3b-174">ERROR_INVALID_PARAMETER</span><span class="sxs-lookup"><span data-stu-id="63b3b-174">ERROR_INVALID_PARAMETER</span></span> | <span data-ttu-id="63b3b-175">87</span><span class="sxs-lookup"><span data-stu-id="63b3b-175">87</span></span> | <span data-ttu-id="63b3b-176">El argumento proporcionado al método no es válido.</span><span class="sxs-lookup"><span data-stu-id="63b3b-176">An argument supplied to the method is invalid.</span></span> |
| <span data-ttu-id="63b3b-177">ERROR_ALREADY_EXISTS</span><span class="sxs-lookup"><span data-stu-id="63b3b-177">ERROR_ALREADY_EXISTS</span></span> | <span data-ttu-id="63b3b-178">183</span><span class="sxs-lookup"><span data-stu-id="63b3b-178">183</span></span> | <span data-ttu-id="63b3b-179">El archivo o directorio ya existe.</span><span class="sxs-lookup"><span data-stu-id="63b3b-179">The file or directory already exists.</span></span> |

<span data-ttu-id="63b3b-180">Puede controlarlos con una cláusula `When` en una instrucción catch, como se muestra en el ejemplo siguiente.</span><span class="sxs-lookup"><span data-stu-id="63b3b-180">You can handle these using a `When` clause in a catch statement, as the following example shows.</span></span>

[!code-csharp[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/cs/io-exceptions.cs)]
[!code-vb[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/vb/io-exceptions.vb)]

## <a name="see-also"></a><span data-ttu-id="63b3b-181">Vea también</span><span class="sxs-lookup"><span data-stu-id="63b3b-181">See also</span></span>

- [<span data-ttu-id="63b3b-182">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="63b3b-182">Handling and throwing exceptions in .NET</span></span>](../exceptions/index.md)
- [<span data-ttu-id="63b3b-183">Control de excepciones (biblioteca TPL)</span><span class="sxs-lookup"><span data-stu-id="63b3b-183">Exception handling (Task Parallel Library)</span></span>](../parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="63b3b-184">Procedimientos recomendados para excepciones</span><span class="sxs-lookup"><span data-stu-id="63b3b-184">Best practices for exceptions</span></span>](../exceptions/best-practices-for-exceptions.md)
- [<span data-ttu-id="63b3b-185">Uso de excepciones específicas en un bloque Catch</span><span class="sxs-lookup"><span data-stu-id="63b3b-185">How to use specific exceptions in a catch block</span></span>](../exceptions/how-to-use-specific-exceptions-in-a-catch-block.md)
